export const REJECT_MAPPING = {
  companyName: 'loanInfo.companyName',
  qualifications: 'loanInfo.qualifications',
  marriage: 'loanInfo.marriage',
  mateName: 'loanInfo.mateName',
  mateMobile: 'loanInfo.urgencyName,loanInfo.urgencyTel',
  mateTel: 'loanInfo.urgencyName,loanInfo.urgencyTel',
  emergencyRelation: 'loanInfo.urgencyRelation',
  emergencyOtherRelation: 'loanInfo.urgencyRelation',
  emergencyTel: 'loanInfo.urgencyTel',
  emergencyOtherTel: 'loanInfo.urgencyTel',
  companyTel: 'loanInfo.companyTel',
  userCellphone: 'loanInfo.contractTel',
  emergencyName: 'loanInfo.urgencyName',
  emergencyOtherName: 'loanInfo.urgencyName',
  socialJob: 'loanInfo.socialJobName',
  companyAddress: 'loanInfo.companyAddr',
  companyAddr: 'loanInfo.companyAddr',
  emergencyAddress: 'loanInfo.urgencyAddr',
  emergencyOtherAddress: 'loanInfo.urgencyAddr',
  userName: 'loanInfo.userName',
  commonName: 'loanInfo.commonName',
  income: 'loanInfo.salary',
};
