@startuml 租房填单流程
skinparam handwritten true;
skinparam backgroundColor #FFFFFF;
skinparam activityBackgroundColor #FFFFFF;
start
:进入OCR填单页面;
if (是否已传过三张照片?) then(false)
  :继续填单;
  :调用OCR验证身份证接口;
else(true)
endif
:调用人脸识别接口;
if (需要进行人脸识别?) then(true)
  :调用人脸识别接口;
else(false)
endif
if (已绑卡?) then(false)
  :进入绑卡页;
  if (驳回修改?) then(true)
    :上传银行卡照片;
  else(false)
    :填写绑卡四要素+银行卡照片;
  endif
else(true)
endif
:进入合同详情页确认合同;
:进入基本信息填写页填写基本信息;
if (是否已婚?) then(true)
  :填写配偶信息;
else (false)
  :填写紧急联系人一信息;
endif
if (是否是学生?) then(true)
  :不填写工作单位相关信息;
else (false)
  :填写工作单位相关信息;
endif
:提交订单;
end
@enduml