@startuml 驳回修改页面跳转
skinparam handwritten true;
skinparam backgroundColor #FFFFFF;
skinparam activityBackgroundColor #FFFFFF;
start
:驳回修改;
if (type === '01') then(true)
  :根据category获取跳转的页面;
else (false)
  :租房修改;
  if (驳回原因有idCard) then(true)
    :跳转至身份证页面;
    if (驳回原因有银行卡) then(true)
      :跳转至绑卡页面上传银行卡照片;
    endif
  elseif (驳回原因有银行卡) then(true)
    :跳转至绑卡页面上传银行卡照片;
  endif
    :跳转至个人信息页面;
endif
  :修改完成;
end
@enduml